runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/.*
  script: admin.app
  login: admin

- url: /orders/.*
  script: orders.app

- url: /.*
  script: main.app

libraries:
- name: pycrypto
  version: "2.6"
